#!/usr/bin/env ruby
# vim:ft=ruby:sw=2:ts=2

require 'json'
require 'optparse'
require 'optparse/time'
require 'rest_client'
require 'time'
require 'uri'

Version = [1,0,0]

options = {
  :date => Time.now
}

OptionParser.new do |opts|
  opts.banner = 'Usage: hccopy [options] [ROOM_NAME] [NUM_ITEMS]'
  opts.on('-d', '--date [DATE]', Time, 'Date on which to copy chat messages') do |date|
    options[:date] = date
  end
  opts.on('-n', '--num-items [NUM_ITEMS]', Integer, 'Number of chat messages to copy - defaults to 25') do |num_items|
    options[:num_items] = num_items
  end
  opts.on('-r', '--room [ROOM_NAME]', 'HipChat room from which to copy chat messages') do |room|
    options[:room] = room
  end
  opts.on('-v', '--[no-]verbose', 'Run verbosely') do |v|
    options[:verbose] = v
  end
  opts.on('--[no-]debug', 'Show debug output') do |debug|
    options[:debug] = debug
  end
  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
  opts.on_tail('--version', 'Show version') do
    puts Version.join('.')
    exit
  end
end.parse!

debug = options[:debug]
verbose = options[:verbose] || options[:debug]
room_name = options[:room] || ARGV[0] || 'Client Services'
num_items = options[:num_items] || ARGV[1] || 25

RestClient.log = 'stdout' if debug

auth_file = File.join(ENV['HOME'], '.hcapi')
if File.exists? auth_file
  auth_token = File.read(auth_file).gsub("\n", ' ').squeeze(' ')
  puts "Auth token: #{auth_token}" if verbose
else
  $stderr.puts '[error]: missing auth token file ~/.hcauth'
  exit 1
end

param_arg = {
  :accept => :json,
  :params => {
    :auth_token => auth_token
  }
}

room_name_esc = URI.escape(room_name)
room_id = 0
RestClient.get("https://api.hipchat.com/v2/room/#{room_name_esc}", param_arg) do |response, request, result|
  json = JSON.parse(response.body)
  room_id = json['id']
  puts "Room '#{room_name}' has ID #{room_id}" if verbose
end

chat_date = options[:date]
puts "Getting history for #{chat_date.to_s}" if verbose

param_arg = {
  :accept => :json,
  :params => {
    :auth_token => auth_token,
    :date => chat_date,
    'max-results' => num_items
  }
}

json = nil
RestClient.get("https://api.hipchat.com/v2/room/#{room_id}/history", param_arg) do |response, request, result|
  json = JSON.parse(response.body)
end

if debug
  chat_json_file = "messages-#{room_id}-#{chat_date.strftime('%Y-%m-%d')}.json"
  File.open(chat_json_file, 'w') { |f| f.write(json.inspect) }
  puts "Chat JSON saved to #{chat_json_file}"
end

items = json['items']
items.each do |item|
  date = Time.parse(item['date']).strftime('%Y-%m-%d %H:%M:%S')
  from = item['from']
  if from.is_a?(Hash)
    name = from['name']
  else
    name = from
  end
  message = item['message']
  puts "#{date} #{name}: #{message}"
end

